sudo: required
services:
  - docker

before_install:
  - docker build -t chivalrysoft/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run chivalrysoft/react-test npm test -- --coverage

after_success:
  - docker build -t chivalrysoft/multi-client ./client
  - docker build -t chivalrysoft/multi-nginx ./nginx
  - docker build -t chivalrysoft/multi-server ./server
  - docker build -t chivalrysoft/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chivalrysoft/multi-client
  - docker push chivalrysoft/multi-nginx
  - docker push chivalrysoft/multi-server
  - docker push chivalrysoft/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-2-399404566115
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
