name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t chivalrysoft/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true chivalrysoft/react-test npm test

      - run: docker build -t chivalrysoft/multi-client ./client
      - run: docker build -t chivalrysoft/multi-nginx ./nginx
      - run: docker build -t chivalrysoft/multi-server ./server
      - run: docker build -t chivalrysoft/multi-worker ./worker

      - run: docker push chivalrysoft/multi-client
      - run: docker push chivalrysoft/multi-nginx
      - run: docker push chivalrysoft/multi-server
      - run: docker push chivalrysoft/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: "${{ secrets.AWS_ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.AWS_SECRET_KEY }}"
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-2-399404566115
          region: us-east-2:wa
          
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
